Port mDNS hostname resolution from 'Angry IP Scanner' + Fix NetBIOS hostname resolution
aaronjwood/PortAuthority pull request #135
Opened 2022-02-04 18:19 UTC by BayLee4

Hi 👋 

In this pull request I ported the mDNS hostname resolution from [Angry IP Scanner](https://github.com/angryip/ipscan) (also GPL licensed) and fixed the NetBIOS hostname resolution which wasn't working for workstations.

Few modification from upstream [MDNSResolver](https://github.com/angryip/ipscan/blob/master/src/net/azib/ipscan/util/MDNSResolver.java), first using `socket.joinGroup(mdnsIP);` which is working on Android and catch more hosts (was disabled because of macOS I guess) :

https://github.com/BayLee4/PortAuthority/blob/4debcfa25a680e2e0e183bca9b95061ccc9a7a99/app/src/main/java/com/aaronjwood/portauthority/utils/MDNSResolver.java#L20

And modify hostnames parsing accordingly : 

https://github.com/BayLee4/PortAuthority/blob/4debcfa25a680e2e0e183bca9b95061ccc9a7a99/app/src/main/java/com/aaronjwood/portauthority/utils/MDNSResolver.java#L73

Regarding the changes to the NetBIOS hostname resolution, we know catch the `NETBIOS_WORKSTATION` name. The default behaviour isn't changed at all, as the `NETBIOS_FILE_SERVER` name is still used in priority if present. 

Both the NetBIOS and mDNS hostname resolution now respects the Lan Socket Timeout setting, which is helpful on slow networks.

The changes in .xml strings are for Android Studio, which refuse to compile without these minor modifications. The rest of the code is commented, but feel free to ask any question!

2022-02-11 13:14 UTC, BayLee4 commented
This last commit implement API 31 compatibility, which fix #125, #129 and #134.
It also update dependencies, drop the outdated `JCIFS` library (last update : 2012!) in favor of [NetBIOSResolver.java](https://github.com/angryip/ipscan/blob/master/src/net/azib/ipscan/util/NetBIOSResolver.java) from [Angry IP Scanner](https://github.com/angryip/ipscan), and fix the CI to accomodate all of these changes. There is also a few other minor improvements, like not showing `.local` suffixes if they exists.

2022-02-21 19:08 UTC, aaronjwood commented
Thanks so much for this! Sorry I have not been responsive, I have not had the time to focus on this project.

2022-02-21 19:26 UTC, aaronjwood requested changes
Thanks again! Just a few comments overall :)

2022-02-21 19:26 UTC, aaronjwood commented on app/src/main/java/com/aaronjwood/portauthority/async/ScanHostsAsyncTask.java
> +                int returnCode = 0;
Could you split this out into a reusable method? I noticed it is the same as the diff above.

2022-02-21 19:26 UTC, aaronjwood commented on app/src/main/java/com/aaronjwood/portauthority/async/ScanHostsAsyncTask.java
> +                        NetBIOSResolver resolver = new NetBIOSResolver(UserPreference.getLanSocketTimeout(ctx));
Can we reuse the code from above here too? It looks like the resolver assignment is the only thing that's different.

2022-02-21 19:26 UTC, aaronjwood commented on app/src/main/java/com/aaronjwood/portauthority/network/Host.java
> +        if (hostname != null && hostname.isEmpty() && hostname.endsWith(".local")) {
`hostname.isEmpty() && hostname.endsWith(".local")` seems like it should be impossible.

2022-02-21 19:26 UTC, aaronjwood commented on app/src/main/java/com/aaronjwood/portauthority/network/Wireless.java
> +            return new String("Not available");
Just curious, what's the reason to do `new String` rather than `""`

2022-02-21 19:26 UTC, aaronjwood commented on app/src/main/java/com/aaronjwood/portauthority/utils/MDNSResolver.java
> +	InetAddress mdnsIP = InetAddress.getByName("224.0.0.251");
Would you mind making this IP a constant somewhere?

2022-02-21 19:26 UTC, aaronjwood commented on app/src/main/java/com/aaronjwood/portauthority/utils/MDNSResolver.java
> +	private int mdnsPort = 5353;
This is probably a good candidate for a constant too.

2022-02-21 19:26 UTC, aaronjwood commented on app/src/main/java/com/aaronjwood/portauthority/utils/MDNSResolver.java
> +		// note: only IPv4 is supported here
Currently the host scanning picks up on IPv6 stuff. At least on my phone in my home network it does due to the way I have my LAN configured. It looks like we will have to disable IPv6 completely due to this limitation.

2022-09-05 23:40 UTC, merged

2022-09-05 23:59 UTC, aaronjwood commented
Thanks for your work on this. I'll merge it in with some clean ups I am currently working on and hopefully get a release out in the next few days :)